# Generated by Django 5.1.1 on 2024-09-15 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyApp', '0003_faculty_sno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='sNo',
        ),
    ]
